#!/bin/bash
#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=setup
#SBATCH --ntasks=1
#SBATCH --time=01:00:00
#SBATCH --output=/home/scur1045/jobs/logs/setup_%A.out

module purge
module load 2023
module load Python/3.11.3-GCCcore-12.3.0

# curl -sSL https://install.python-poetry.org | python3 -

poetry config virtualenvs.create true
poetry config virtualenvs.in-project true
poetry install